config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :items do
    member do
      patch :complete
    end
  end 
  root 'items#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :user

    def completed?
        !completed_at.blank?
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    before_action :find_item, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!
    def index
        if user_signed_in?
        @items = Item.where(:user_id => current_user.id).order("created_at DESC")
        end
    end

    def new
        @item = current_user.items.build
    end

    def show 
    end

    def create
        @item = current_user.items.build(items_params)
        if @item.save
            redirect_to root_path, notice: 'Item added to todolist!'
        else
            render :new,status: :unprocessable_entity 
        end
    end


    def edit
    end

    def update
        if @item.update(items_params)
            redirect_to root_path, notice: 'Item updated!'
        end
    end

    def complete
        @item = Item.find(params[:id])
        @item.update_attribute(:completed_at, Time.now)
        redirect_to root_path
    end



    def destroy
         @item.destroy
         redirect_to root_path, alert: 'Item removed from todolist!'
    end
    private
    def items_params
        params.require(:item).permit(:title, :description)
    end

    def find_item
        @item = Item.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
    <%= simple_form_for @item do |f|%>
    <%= f.input :title, label: "Item" %>
    <%= f.input :description %>
    <%= f.button :submit %>
    <% end %>

app/views/items/edit.html.erb
    <h1>Edit Todolist Item</h1>
    <%= render'form' %>

app/views/items/index.html.erb
<% if user_signed_in? %>
 <div class="col-md-6 col-md-offset-3">
  <% @items.each do |item| %>
   <% if item.completed? %>
            <div class="jumbotron">
              <h2 style="opacity: 0.5;"><strike><%= link_to item.title, item %></strike></h2>
              <p style="opacity: 0.5;"><%= item.description %></p>
              <p>Completed <%= time_ago_in_words(item.completed_at) %> ago</p>
              <div class="row item">
                  <div class="col-md-2">
                    <div class="row item">
                      <p> <%= link_to  item,data: {turbo_method: :delete, turbo_confirm: 'Are you sure?', method: :delete} do %></p>
                        <i class="fa fa-lg fa-trash"></i>
                        <% end %>
                    </div>    
                  </div>     
              </div>       
   <% else %>
        <div class="jumbotron">
          <h2><%= link_to item.title, item %></h2>
          <p><%= item.description %></p>
          <p>Created <%= time_ago_in_words(item.created_at) %> ago</p>
          <div class="row item">
              <div class="col-md-2">
                  <p><%= link_to complete_item_path(item),data: { 'turbo-method': :patch }, method: :patch do %></p>
                    <i class="fa fa-lg fa-check"></i>
                  <% end %>
              </div>
              
              <div class="col-md-2">
                <div class="row item">
                  <p> <%= link_to edit_item_path(item)  do%></p>
                    <i class="fa fa-lg fa-edit"></i>
                  <% end %>
                </div>    
              </div>     
              <div class="col-md-2">
                <div class="row item">
                  <p> <%= link_to  item,data: {turbo_method: :delete, turbo_confirm: 'Are you sure?', method: :delete} do %></p>
                    <i class="fa fa-lg fa-trash"></i>
                    <% end %>
                </div>    
              </div>     
          </div>   
          <% end %>
        </div>
    <% end %>
    
 </div>
<% else %>
  <%= render 'partials/landingpage' %>
<% end %>

app/views/items/new.html.erb
    <h1>New Todolist Item</h1>
    <%= render 'form' %>

app/views/items/show.html.erb
        <div class="jumbotron">
            <h2><%= @item.title %></h2>
            <p><%= @item.description %></p>
            <% if @item.completed? %>
                <p style="opacity: 0.5;">Has already been completed</p>
            <% else %>
                <h5 style="opacity: 0.5;">Has not been completed yet!</h5>
            <% end %>
        </div>

            <%= link_to "Back", root_path, class: 'btn btn-secondary' %>
            <%= link_to "Edit", edit_item_path(@item), class: 'btn btn-secondary' %>
            <%= link_to 'Destroy', @item,data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} , class: 'btn btn-secondary'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" integrity="sha384-rOA1PnstxnOBLzCLMcre8ybwbTmemjzdNlILg8O7z1lUkLXozs4DHonlDtnE7fpc" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'partials/navbar' %>
    <div class="container">
      <%= render 'partials/alerts' %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/partials/_alerts.html.erb
<% if flash[:notice] %>
    <div  class="alert alert-success" role="alert">
        <%=  flash[:notice]%>
    </div>
<% end %>
<% if flash[:alert] %>
    <div class="alert alert-danger" >
        <%=  flash[:alert]%>
    </div>
<% end %>

app/views/partials/_landingpage.html.erb
<div class="container">  
    <div class="jumbotron"> 
            <h1>Welcome to your Todolist!</h1>
            <p>Keep track of your daily stuff!</p>
            <%= link_to "SignUp", new_user_registration_path, class: 'btn btn-primary'%>
            <%= link_to "SignIn", new_user_session_path , class: 'btn btn-primary'%>
    </div>
</div>

app/views/partials/_navbar.html.erb
<div class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <%= link_to "Todolist",root_path,class: 'navbar-brand' %>
        </div>
        <ul class="nav navbar-nav">
            <% if current_user.present? %>
              <li><%= link_to "New Item", new_item_path %></li>
            <% else%>
             <li><%= link_to "Sign Up", new_user_registration_path %></li>
             <li><%= link_to "Login", new_user_session_path %></li>
             <% end %>
         </ul>
         <% if user_signed_in? %>
                <%= link_to 'Signout', destroy_user_session_path(@user),
         data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: 'navbar-text navbar-link navbar-right' %>
         <% end %>
         <% if user_signed_in? %>
            <%= link_to current_user.email, edit_user_registration_path, class: 'navbar-text navbar-link navbar-right' %>
         <% end %>
        </div>
    </div>
    